In [79]:
#!/usr/bin/python

import sys
import pickle
sys.path.append("../tools/")

import pandas as pd
import numpy as np
from collections import Counter
pd.options.display.max_columns = 100
from feature_format import featureFormat, targetFeatureSplit
from tester import dump_classifier_and_data

### Load the dictionary containing the dataset
with open("final_project_dataset.pkl", "r") as data_file:
    data_dict = pickle.load(data_file)

In [68]:
# List of features to choose from
print len(data_dict)
available_features = data_dict.values()[0].keys()
available_features

146

['salary',
 'to_messages',
 'deferral_payments',
 'total_payments',
 'exercised_stock_options',
 'bonus',
 'restricted_stock',
 'shared_receipt_with_poi',
 'restricted_stock_deferred',
 'total_stock_value',
 'expenses',
 'loan_advances',
 'from_messages',
 'other',
 'from_this_person_to_poi',
 'poi',
 'director_fees',
 'deferred_income',
 'long_term_incentive',
 'email_address',
 'from_poi_to_this_person']

In [99]:
raw_df = pd.DataFrame(data_dict.values(),index=data_dict.keys())
raw_df.head(2)

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
METTS MARK,600000,NaN,NaN,NaN,mark.metts@enron.com,NaN,94299,29,38,1,NaN,NaN,1740,False,585062,NaN,365788,702,807,1061827,585062
BAXTER JOHN C,1200000,1295738,-1386055,NaN,NaN,6680544,11200,NaN,NaN,NaN,NaN,1586055,2660303,False,3942714,NaN,267102,NaN,NaN,5634343,10623258

In [100]:
def convert_to_zero(x):
    if x == 'NaN':
        return 0
    else:
        return x
for feature in available_features:
    raw_df[feature] = raw_df[feature].apply(convert_to_zero)

In [105]:
raw_df.sort_values(by='poi',ascending=False)

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
GLISAN JR BEN F,600000,0,0,0,ben.glisan@enron.com,384728,125978,16,52,6,0,71023,200308,True,393818,0,274975,874,873,1272284,778546
COLWELL WESLEY,1200000,27610,-144062,0,wes.colwell@enron.com,0,16514,40,240,11,0,0,101740,True,698242,0,288542,1132,1758,1490344,698242
BELDEN TIMOTHY N,5249999,2144013,-2334434,0,tim.belden@enron.com,953136,17355,484,228,108,0,0,210698,True,157569,0,213999,5521,7991,5501630,1110705
FASTOW ANDREW S,1300000,0,-1386055,0,andrew.fastow@enron.com,0,55921,0,0,0,0,1736055,277464,True,1794412,0,440698,0,0,2424083,1794412
CALGER CHRISTOPHER F,1250000,0,-262500,0,christopher.calger@enron.com,0,35818,144,199,25,0,375304,486,True,126027,0,240189,2188,2598,1639297,126027
LAY KENNETH L,7000000,202911,-300000,0,kenneth.lay@enron.com,34348384,99832,36,123,16,81525000,3600000,10359729,True,14761694,0,1072321,2411,4273,103559793,49110078
RICE KENNETH D,1750000,0,-3504386,0,ken.rice@enron.com,19794175,46950,18,42,4,0,1617011,174839,True,2748364,0,420636,864,905,505050,22542539
DELAINEY DAVID W,3000000,0,0,0,david.delainey@enron.com,2291113,86174,3069,66,609,0,1294981,1661,True,1323148,0,365163,2097,3093,4747979,3614261
SKILLING JEFFREY K,5600000,0,0,0,jeff.skilling@enron.com,19250000,29336,108,88,30,0,1920000,22122,True,6843672,0,1111258,2042,3627,8682716,26093672
SHELBY REX,200000,0,-4167,0,rex.shelby@enron.com,1624396,22884,39,13,14,0,0,1573324,True,869220,0,211844,91,225,2003885,2493616
KOPPER MICHAEL J,800000,0,0,0,michael.kopper@enron.com,0,118134,0,0,0,0,602671,907502,True,985032,0,224305,0,0,2652612,985032
RIEKER PAULA H,700000,214678,-100000,0,paula.rieker@enron.com,1635238,33271,82,35,48,0,0,1950,True,283649,0,249201,1258,1328,1099100,1918887
YEAGER F SCOTT,0,0,0,0,scott.yeager@enron.com,8308552,53947,0,0,0,0,0,147950,True,3576206,0,158403,0,0,360300,11884758
HIRKO JOSEPH,0,10259,0,0,joe.hirko@enron.com,30766064,77978,0,0,0,0,0,2856,True,0,0,0,0,0,91093,30766064
BOWEN JR RAYMOND M,1350000,0,-833,0,raymond.bowen@enron.com,0,65907,27,140,15,0,974293,1621,True,252055,0,278601,1593,1858,2669589,252055
KOENIG MARK E,700000,0,0,0,mark.koenig@enron.com,671737,127017,61,53,15,0,300000,150458,True,1248318,0,309946,2271,2374,1587421,1920055
CAUSEY RICHARD A,1000000,0,-235000,0,richard.causey@enron.com,0,30674,49,58,12,0,350000,307895,True,2502063,0,415189,1585,1892,1868758,2502063
HANNON KEVIN P,1500000,0,-3117011,0,kevin.hannon@enron.com,5538001,34039,32,32,21,0,1617011,11350,True,853064,0,243293,1035,1045,288682,6391065
BLAKE JR. NORMAN P,0,0,-113784,113784,0,0,1279,0,0,0,0,0,0,False,0,0,0,0,0,1279,0
OVERDYKE JR JERE C,0,0,0,0,jere.overdyke@enron.com,5266578,18834,0,0,0,0,135836,176,False,2041016,0,94941,0,0,249787,7307594
PEREIRA PAULO V. FERRAZ,0,0,-101250,101250,0,0,27942,0,0,0,0,0,0,False,0,0,0,0,0,27942,0
STABLER FRANK,500000,0,0,0,frank.stabler@enron.com,0,16514,0,0,0,0,0,356071,False,511734,0,239502,0,0,1112087,511734
MARTIN AMANDA K,0,85430,0,0,a..martin@enron.com,2070306,8211,230,8,0,0,5145434,2818454,False,0,0,349487,477,1522,8407016,2070306
HAYSLETT RODERICK J,0,0,0,0,rod.hayslett@enron.com,0,0,1061,35,38,0,0,0,False,346663,0,0,571,2649,0,346663
COX DAVID,800000,0,-41250,0,chip.cox@enron.com,117551,27861,33,0,4,0,0,494,False,378082,0,314288,71,102,1101393,495633
SHERRICK JEFFREY B,0,0,0,0,jeffrey.sherrick@enron.com,1426469,0,25,39,18,0,0,0,False,405999,0,0,583,613,0,1832468
TILNEY ELIZABETH A,300000,0,-575000,0,elizabeth.tilney@enron.com,591250,0,19,10,11,0,275000,152055,False,576792,0,247338,379,460,399393,1168042
PRENTICE JAMES,0,564348,0,0,james.prentice@enron.com,886231,0,0,0,0,0,0,0,False,208809,0,0,0,0,564348,1095040
GRAY RODNEY,0,93585,0,0,0,0,0,0,0,0,0,365625,680833,False,0,0,6615,0,0,1146658,0
PICKERING MARK R,300000,0,0,0,mark.pickering@enron.com,28798,31653,67,7,0,400000,0,0,False,0,0,655037,728,898,1386690,28798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HERMANN ROBERT J,700000,0,-280000,0,robert.hermann@enron.com,187500,48357,0,0,0,0,150000,416441,False,480632,0,262663,0,0,1297461,668132
MCCLELLAN GEORGE,900000,0,-125000,0,george.mcclellan@enron.com,506765,228763,49,52,0,0,0,51587,False,441096,0,263413,1469,1744,1318763,947861
GAHN ROBERT S,509870,73122,-1042,0,0,83237,50080,0,0,0,0,0,76547,False,235370,0,192008,0,0,900585,318607
CUMBERLAND MICHAEL S,325000,0,0,0,0,0,22344,0,0,0,0,275000,713,False,207940,0,184899,0,0,807956,207940
MCDONALD REBECCA,0,0,0,0,rebecca.mcdonald@enron.com,757301,0,13,54,1,0,0,0,False,934065,0,0,720,894,0,1691366
OLSON CINDY K,750000,77716,0,0,cindy.olson@enron.com,1637034,63791,52,20,15,0,100000,972,False,969729,0,329078,856,1184,1321557,2606763
BUTTS ROBERT H,750000,0,-75000,0,bob.butts@enron.com,0,9410,0,0,0,0,175000,150656,False,417619,0,261516,0,0,1271582,417619
MEYER JEROME J,0,0,-38346,38346,0,0,2151,0,0,0,0,0,0,False,0,0,0,0,0,2151,0
LINDHOLM TOD A,200000,204075,0,0,tod.lindholm@enron.com,2549361,57727,0,0,0,0,175000,2630,False,514847,0,236457,0,0,875889,3064208
WROBEL BRUCE,0,0,0,0,0,139130,0,0,0,0,0,0,0,False,0,0,0,0,0,0,139130
SULLIVAN-SHAKLOVITZ COLLEEN,100000,181993,0,0,0,1362375,0,0,0,0,0,554422,162,False,0,0,162779,0,0,999356,1362375
PIRO JIM,0,0,0,0,jim.piro@enron.com,0,0,16,0,1,0,0,0,False,47304,0,0,3,58,0,47304
MCCONNELL MICHAEL S,1100000,0,0,0,mike.mcconnell@enron.com,1623010,81364,2742,92,194,0,554422,540,False,1478269,0,365038,2189,3329,2101364,3101279
KISHKILL JOSEPH G,0,0,-51042,0,joe.kishkill@enron.com,0,116335,0,0,0,0,0,465357,False,1034346,0,174246,0,0,704896,1034346
HAYES ROBERT E,0,7961,0,0,robert.hayes@enron.com,0,0,12,16,0,0,0,0,False,151418,0,0,50,504,7961,151418
DEFFNER JOSEPH M,600000,0,0,0,joseph.deffner@enron.com,17378,41626,74,115,4,0,335349,25553,False,141833,0,206121,552,714,1208649,159211
LEMAISTRE CHARLES,0,0,-25000,112492,0,412878,0,0,0,0,0,0,0,False,0,0,0,0,0,87492,412878
SHERRIFF JOHN R,1500000,0,0,0,john.sherriff@enron.com,1835558,0,92,28,23,0,554422,1852186,False,1293424,0,428780,2103,3187,4335388,3128982
SHAPIRO RICHARD S,650000,0,0,0,richard.shapiro@enron.com,607837,137767,1215,74,65,0,0,705,False,379164,0,269076,4527,15149,1057548,987001
DUNCAN JOHN H,0,0,-25000,102492,0,371750,0,0,0,0,0,0,0,False,0,0,0,0,0,77492,371750
BANNANTINE JAMES M,0,0,-5104,0,james.bannantine@enron.com,4046157,56301,29,39,0,0,0,864523,False,1757552,-560222,477,465,566,916197,5243487
GOLD JOSEPH,750000,0,0,0,joe.gold@enron.com,436515,0,0,0,0,0,304805,819288,False,441096,0,272880,0,0,2146973,877611
POWERS WILLIAM,0,0,-17500,17500,ken.powers@enron.com,0,0,26,0,0,0,0,0,False,0,0,0,12,653,0,0
WAKEHAM JOHN,0,0,0,109298,0,0,103773,0,0,0,0,0,0,False,0,0,0,0,0,213071,0
DETMERING TIMOTHY J,425000,875307,-775241,0,timothy.detmering@enron.com,2027865,52255,0,0,0,0,415657,1105,False,315068,-315068,210500,0,0,1204583,2027865
BERBERIAN DAVID,0,0,0,0,david.berberian@enron.com,1624396,11892,0,0,0,0,0,0,False,869220,0,216582,0,0,228474,2493616
LAVORATO JOHN J,8000000,0,0,0,john.lavorato@enron.com,4158995,49537,2585,528,411,0,2035380,1552,False,1008149,0,339288,3962,7259,10425757,5167144
LEFF DANIEL P,1000000,0,0,0,dan.leff@enron.com,0,0,63,67,14,0,1387399,3083,False,360528,0,273746,2672,2822,2664228,360528
MCCARTY DANNY J,0,0,0,0,danny.mccarty@enron.com,664375,0,215,25,2,0,0,0,False,94556,0,0,508,1433,0,758931
SCRIMSHAW MATTHEW,0,0,0,0,matthew.scrimshaw@enron.com,759557,0,0,0,0,0,0,0,False,0,0,0,0,0,0,759557

In [104]:
raw_df[['salary','bonus',
        'long_term_incentive',
        'from_this_person_to_poi',
        'from_poi_to_this_person',
        'poi']].sort_values(by='poi',ascending =False)

,salary,bonus,long_term_incentive,from_this_person_to_poi,from_poi_to_this_person,poi
GLISAN JR BEN F,274975,600000,71023,6,52,True
COLWELL WESLEY,288542,1200000,0,11,240,True
BELDEN TIMOTHY N,213999,5249999,0,108,228,True
FASTOW ANDREW S,440698,1300000,1736055,0,0,True
CALGER CHRISTOPHER F,240189,1250000,375304,25,199,True
LAY KENNETH L,1072321,7000000,3600000,16,123,True
RICE KENNETH D,420636,1750000,1617011,4,42,True
DELAINEY DAVID W,365163,3000000,1294981,609,66,True
SKILLING JEFFREY K,1111258,5600000,1920000,30,88,True
SHELBY REX,211844,200000,0,14,13,True
KOPPER MICHAEL J,224305,800000,602671,0,0,True
RIEKER PAULA H,249201,700000,0,48,35,True
YEAGER F SCOTT,158403,0,0,0,0,True
HIRKO JOSEPH,0,0,0,0,0,True
BOWEN JR RAYMOND M,278601,1350000,974293,15,140,True
KOENIG MARK E,309946,700000,300000,15,53,True
CAUSEY RICHARD A,415189,1000000,350000,12,58,True
HANNON KEVIN P,243293,1500000,1617011,21,32,True
BLAKE JR. NORMAN P,0,0,0,0,0,False
OVERDYKE JR JERE C,94941,0,135836,0,0,False
PEREIRA PAULO V. FERRAZ,0,0,0,0,0,False
STABLER FRANK,239502,500000,0,0,0,False
MARTIN AMANDA K,349487,0,5145434,0,8,False
HAYSLETT RODERICK J,0,0,0,38,35,False
COX DAVID,314288,800000,0,4,0,False
SHERRICK JEFFREY B,0,0,0,18,39,False
TILNEY ELIZABETH A,247338,300000,275000,11,10,False
PRENTICE JAMES,0,0,0,0,0,False
GRAY RODNEY,6615,0,365625,0,0,False
PICKERING MARK R,655037,300000,0,0,7,False
...,...,...,...,...,...,...
HERMANN ROBERT J,262663,700000,150000,0,0,False
MCCLELLAN GEORGE,263413,900000,0,0,52,False
GAHN ROBERT S,192008,509870,0,0,0,False
CUMBERLAND MICHAEL S,184899,325000,275000,0,0,False
MCDONALD REBECCA,0,0,0,1,54,False
OLSON CINDY K,329078,750000,100000,15,20,False
BUTTS ROBERT H,261516,750000,175000,0,0,False
MEYER JEROME J,0,0,0,0,0,False
LINDHOLM TOD A,236457,200000,175000,0,0,False
WROBEL BRUCE,0,0,0,0,0,False
SULLIVAN-SHAKLOVITZ COLLEEN,162779,100000,554422,0,0,False
PIRO JIM,0,0,0,1,0,False
MCCONNELL MICHAEL S,365038,1100000,554422,194,92,False
KISHKILL JOSEPH G,174246,0,0,0,0,False
HAYES ROBERT E,0,0,0,0,16,False
DEFFNER JOSEPH M,206121,600000,335349,4,115,False
LEMAISTRE CHARLES,0,0,0,0,0,False
SHERRIFF JOHN R,428780,1500000,554422,23,28,False
SHAPIRO RICHARD S,269076,650000,0,65,74,False
DUNCAN JOHN H,0,0,0,0,0,False
BANNANTINE JAMES M,477,0,0,0,39,False
GOLD JOSEPH,272880,750000,304805,0,0,False
POWERS WILLIAM,0,0,0,0,0,False
WAKEHAM JOHN,0,0,0,0,0,False
DETMERING TIMOTHY J,210500,425000,415657,0,0,False
BERBERIAN DAVID,216582,0,0,0,0,False
LAVORATO JOHN J,339288,8000000,2035380,411,528,False
LEFF DANIEL P,273746,1000000,1387399,14,67,False
MCCARTY DANNY J,0,0,0,2,25,False
SCRIMSHAW MATTHEW,0,0,0,0,0,False

In [88]:
raw_df.describe()

       from_poi_to_this_person  from_this_person_to_poi
count               146.000000               146.000000
mean                 38.226027                24.287671
std                  73.901124                79.278206
min                   0.000000                 0.000000
25%                   0.000000                 0.000000
50%                   2.500000                 0.000000
75%                  40.750000                13.750000
max                 528.000000               609.000000

In [49]:
Counter(raw_df['poi'])

Counter({False: 128, True: 18})

In [72]:
for feature in available_features:
    if feature == 'poi':
        pass
    else:
        print '{}: {}'.format(feature,len(raw_df[raw_df[feature]=='NaN']))

salary: 51
to_messages: 60
deferral_payments: 107
total_payments: 21
exercised_stock_options: 44
bonus: 64
restricted_stock: 36
shared_receipt_with_poi: 60
restricted_stock_deferred: 128
total_stock_value: 20
expenses: 51
loan_advances: 142
from_messages: 60
other: 53
from_this_person_to_poi: 60
director_fees: 129
deferred_income: 97
long_term_incentive: 80
email_address: 35
from_poi_to_this_person: 60

In [ ]:
### Task 1: Select what features you'll use.
### features_list is a list of strings, each of which is a feature name.
### The first feature must be "poi".
features_list = ['poi','salary'] # You will need to use more features

In [ ]:
### Task 2: Remove outliers

In [ ]:
### Task 3: Create new feature(s)
### Store to my_dataset for easy export below.
my_dataset = data_dict

### Extract features and labels from dataset for local testing
data = featureFormat(my_dataset, features_list, sort_keys = True)
labels, features = targetFeatureSplit(data)

In [ ]:
### Task 4: Try a varity of classifiers
### Please name your classifier clf for easy export below.
### Note that if you want to do PCA or other multi-stage operations,
### you'll need to use Pipelines. For more info:
### http://scikit-learn.org/stable/modules/pipeline.html

# Provided to give you a starting point. Try a variety of classifiers.
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()

In [ ]:
### Task 5: Tune your classifier to achieve better than .3 precision and recall 
### using our testing script. Check the tester.py script in the final project
### folder for details on the evaluation method, especially the test_classifier
### function. Because of the small size of the dataset, the script uses
### stratified shuffle split cross validation. For more info: 
### http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.StratifiedShuffleSplit.html

# Example starting point. Try investigating other evaluation techniques!
from sklearn.cross_validation import train_test_split
features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

In [ ]:
### Task 6: Dump your classifier, dataset, and features_list so anyone can
### check your results. You do not need to change anything below, but make sure
### that the version of poi_id.py that you submit can be run on its own and
### generates the necessary .pkl files for validating your results.

dump_classifier_and_data(clf, my_dataset, features_list)